# Generated by Django 3.2.13 on 2022-06-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commnt',
            fields=[
                ('commnt_sno', models.AutoField(primary_key=True, serialize=False)),
                ('contnt', models.CharField(max_length=300)),
                ('dt', models.DateField()),
                ('brd_sno', models.ForeignKey(db_column='brd_sno', on_delete=django.db.models.deletion.CASCADE, to='board.brd')),
                ('usr_sno', models.ForeignKey(db_column='usr_sno', on_delete=django.db.models.deletion.CASCADE, to='user.usr')),
            ],
        ),
    ]
