# Generated by Django 3.2.13 on 2022-06-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brd',
            fields=[
                ('brd_sno', models.AutoField(primary_key=True, serialize=False)),
                ('ttl', models.CharField(max_length=100)),
                ('cntnt', models.CharField(max_length=300)),
                ('dt', models.DateField()),
                ('clck', models.IntegerField(default=0)),
                ('usr_sno', models.ForeignKey(db_column='usr_sno', on_delete=django.db.models.deletion.CASCADE, to='user.usr')),
            ],
        ),
        migrations.CreateModel(
            name='Fl',
            fields=[
                ('fl_sno', models.AutoField(primary_key=True, serialize=False)),
                ('orgnl_fnm', models.CharField(max_length=100)),
                ('fnm', models.CharField(max_length=150)),
                ('brd_sno', models.ForeignKey(db_column='brd_sno', on_delete=django.db.models.deletion.CASCADE, to='board.brd')),
                ('usr_sno', models.ForeignKey(db_column='usr_sno', on_delete=django.db.models.deletion.CASCADE, to='user.usr')),
            ],
        ),
    ]
