# Generated by Django 3.2.13 on 2022-06-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('usr_sno', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('nm', models.CharField(max_length=100)),
                ('eml', models.CharField(max_length=100)),
                ('sgnup_dt', models.DateField()),
            ],
        ),
    ]
